### ISSUE TITLE
Issues with unit tests for node

### ISSUE THREAD

**Issue by himalayafan** [kazupon/vue-plugin-boilerplate#2]
Really great starter boilerplate for Vue! However, I was missing a way of running unit tests on the server.
When I try to set it up to run mocha through package.json, it all fails. I had to add a .babelrc file and use the normal ES2015-preset to get it to work. 

However. That again screwed up Rollup.

Any idea how to set this up so I can run my unit tests with mocha not through Karma?

**Comment by kazupon** [comment]
support unit test and e2e.
https://github.com/kazupon/vue-plugin-boilerplate/releases/tag/v3.0.0
